-- AlterTable
ALTER TABLE `returns` ADD COLUMN `category` ENUM('DAMAGED', 'WRONG_ITEM', 'NOT_AS_DESCRIBED', 'NO_LONGER_NEEDED', 'ARRIVED_LATE', 'OTHER') NULL,
    ADD COLUMN `rejection_reason` VARCHAR(500) NULL;
