-- URG-028: per-product barcode opt-in and its symbology.
--
-- Both additive and nullable, so every existing row keeps its current
-- behaviour: NULL `has_barcode` means "never asked" (the same three-state
-- contract as has_variants/has_colors), and NULL `barcode_type` is what makes
-- a pre-existing code "unclassified, shown for review" rather than
-- retroactively invalid. No backfill: inventing a symbology for a code nobody
-- classified is exactly the fabrication this column exists to avoid.
--
-- Generated by `prisma migrate diff` (pure schema diff), never `migrate dev`.

-- AlterTable
ALTER TABLE `products` ADD COLUMN `barcode_type` VARCHAR(16) NULL,
    ADD COLUMN `has_barcode` BOOLEAN NULL;
