-- AlterTable
ALTER TABLE `delivery_assignments` ADD COLUMN `attempt_count` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `failure_reason` VARCHAR(255) NULL,
    MODIFY `status` ENUM('ASSIGNED', 'PICKED_UP', 'OUT_FOR_DELIVERY', 'DELIVERED', 'HANDED_OVER', 'CANCELED', 'RETURNED', 'FAILED_ATTEMPT') NOT NULL DEFAULT 'ASSIGNED';
