-- AlterTable
ALTER TABLE `user_branches` MODIFY `role` ENUM('DEVELOPER', 'OWNER', 'MANAGER', 'FULFILLMENT', 'CASHIER', 'SUPPORT', 'DEMO') NOT NULL;

-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('DEVELOPER', 'OWNER', 'MANAGER', 'FULFILLMENT', 'CASHIER', 'SUPPORT', 'DEMO') NOT NULL DEFAULT 'MANAGER';

